# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_initial_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_to_year',
            name='term1_end',
        ),
        migrations.RemoveField(
            model_name='user_to_year',
            name='term1_start',
        ),
        migrations.RemoveField(
            model_name='user_to_year',
            name='term2_end',
        ),
        migrations.RemoveField(
            model_name='user_to_year',
            name='term2_start',
        ),
        migrations.RemoveField(
            model_name='user_to_year',
            name='term3_end',
        ),
        migrations.RemoveField(
            model_name='user_to_year',
            name='term3_start',
        ),
        migrations.RemoveField(
            model_name='user_to_year',
            name='term4_end',
        ),
        migrations.RemoveField(
            model_name='user_to_year',
            name='term4_start',
        ),
        migrations.AddField(
            model_name='user_to_year',
            name='term1_days',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_to_year',
            name='term2_days',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_to_year',
            name='term3_days',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_to_year',
            name='term4_days',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
