# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_school_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_subject',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plan.subject_info'),
            preserve_default=False,
        ),
    ]
