# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0008_cls_info_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='syllabus',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
