# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0009_topics_syllabus'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('student_surname', models.CharField(max_length=100)),
                ('student_gender', models.CharField(max_length=6)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.cls_info')),
            ],
        ),
    ]
