# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0010_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_name',
        ),
        migrations.AddField(
            model_name='student',
            name='school_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plan.school_subject'),
            preserve_default=False,
        ),
    ]
