# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0012_auto_20171101_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='content',
            fields=[
                ('content_number', models.AutoField(primary_key=True, serialize=False)),
                ('content_value', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='topic',
            fields=[
                ('topic_number', models.AutoField(primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.RenameModel(
            old_name='topics',
            new_name='unit',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='topic_name',
            new_name='unit_name',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='topic_number',
            new_name='unit_number',
        ),
        migrations.AlterField(
            model_name='cls_info',
            name='profile',
            field=models.ImageField(upload_to='./plan/static/plan/photos/', verbose_name='profile_pic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.unit'),
        ),
        migrations.AddField(
            model_name='content',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.topic'),
        ),
    ]
